# Generated by Django 5.1.1 on 2025-09-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_siembra', models.DateField()),
                ('estado', models.CharField(choices=[('semilla', 'Semilla'), ('crecimiento', 'En Crecimiento'), ('cosecha', 'Listo para Cosechar')], default='semilla', max_length=20)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='huerto.sector')),
            ],
        ),
    ]
